# Generated by Django 6.0.4 on 2026-07-01 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_testuserapplication_status_invite"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="trial_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
