# Generated by Django 6.0.4 on 2026-05-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="receipt_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
