# Generated by Django 6.0.4 on 2026-05-01 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def create_default_lists_and_link_expenses(apps, schema_editor):
    User = apps.get_model("users", "User")
    ExpenseList = apps.get_model("expenses", "ExpenseList")
    Expense = apps.get_model("expenses", "Expense")
    for user in User.objects.all():
        default_list = ExpenseList.objects.filter(user=user, is_default=True).first()
        if not default_list:
            default_list = ExpenseList.objects.create(
                user=user, name="Private list", is_default=True
            )
        Expense.objects.filter(user=user, expense_list__isnull=True).update(
            expense_list=default_list
        )


def unlink_expense_lists(apps, schema_editor):
    Expense = apps.get_model("expenses", "Expense")
    Expense.objects.all().update(expense_list=None)


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_add_receipt_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("is_default", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="expense_lists",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-is_default", "name"],
            },
        ),
        migrations.AddField(
            model_name="expense",
            name="expense_list",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="expenses",
                to="expenses.expenselist",
            ),
        ),
        migrations.AddConstraint(
            model_name="expenselist",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("user",),
                name="expense_list_one_default_per_user",
            ),
        ),
        migrations.RunPython(
            create_default_lists_and_link_expenses,
            unlink_expense_lists,
        ),
    ]
